apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: webserver
    spec:
      containers:
      - image: nginx:alpine
        name: webserver
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /etc/nginx # mount nginx-conf volumn to /etc/nginx
          readOnly: true
          name: nginx-conf
        - mountPath: /var/log/nginx
          name: log
      restartPolicy: Always
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf # place ConfigMap `nginx-conf` on /etc/nginx
      - name: log
        emptyDir: {}
          
      
      
